baseurl: ''
markdown : kramdown
exclude: 
  - 'README.md'
  - .asset-cache
  - .bundle
  - assets/manifest.json
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - assets
  - manifest.json

permalink: pretty
title: 'VA ReLAUNCH'

defaults:
  - scope:
      path: "images"
    values:
      image: true